--- # file: roles/lxr/tasks/111-tweak_os_RedHat7.yml

# Tweak OS settings for Lxr

# Assumed remote_user: root

# ---- SELinux settings ----

- name: setup,os_settings | check if selinux is installed
  stat: path=/etc/selinux/config
  register: selinux_config

- name: setup,os_settings | ensure the system has libselinux-python
  yum: name=libselinux-python state=present
  when: selinux_config.stat.exists

- name: setup,os_settings | disable selinux in the config file
  selinux: state=disabled
  when: selinux_config.stat.exists

- name: setup,os_settings | check if a reboot is required
  command: getenforce
  register: selinux_state
  changed_when: False
  when: selinux_config.stat.exists

- name: setup,os_settings | bailing out for a reboot
  fail: msg="Reboot the system and rerun the playbook after that."
  when: selinux_config.stat.exists and selinux_state.stdout != "Disabled"


# ---- Firewall settings ----

- name: setup,os_settings | check if firewalld is running
  command: systemctl is-active firewalld
  register: firewalld_result
  changed_when: False
  ignore_errors: True  # rc will be 3 when inactive

- name: setup,os_settings | open httpd port
  firewalld: permanent={{ item }} port={{ httpd_port }}/tcp state=enabled
  with_items: [ True, False ]
  when: firewalld_result.stdout == "active"


# ---- Lxr_user settings ----

- name: setup,os_settings | setup the user for lxr
  user: name="{{ lxr_user }}" state=present

- name: setup,os_settings | register ssh public key to lxr_user
  authorized_key: user="{{ lxr_user }}" key="{{ lxr_user_login_pubkey }}"

