--- # file: roles/lxr/tasks/111-tweak_os_RedHat7.yml

# Tweak OS settings for Lxr

# Assumed remote_user: root

- name: setup,os_settings | ensure the system has libselinux-python
  yum: name=libselinux-python state=present


# ---- SELinux settings ----

- name: setup,os_settings | disable selinux in the config file
  selinux: state=disabled

- name: setup,os_settings | check if a reboot is required
  command: getenforce
  register: selinux_state
  changed_when: False

- name: setup,os_settings | bailing out for a reboot
  fail: msg="Reboot the system and rerun the playbook after that."
  when: selinux_state.stdout != "Disabled"


# ---- Firewall settings ----

- name: setup,os_settings | open httpd port
  firewalld: permanent=yes port={{ httpd_port }}/tcp state=enabled
  notify: reload firewalld


# ---- Lxr_user settings ----

- name: setup,os_settings | setup the user for lxr
  user: name="{{ lxr_user }}" state=present

- name: setup,os_settings | register ssh public key to lxr_user
  authorized_key: user="{{ lxr_user }}" key="{{ lxr_user_login_pubkey }}"

