--- # file: roles/lxr/tasks/140-install_glimpse.yml

# Install Glimpse to lxr_user's home directory

# Assumed remote_user: {{ lxr_user }}

- name: setup | glimpse | check if the binary exists
  stat: path={{ glimpse_bin }}
  register: st
  when: lxr_use_search_engine == "glimpse"

- name: setup | glimpse | notice about the tarball
  debug: msg="If the remote tarball is changed,
              sha256sum(csum) must be updated by hand."
  when: lxr_use_search_engine == "glimpse"

- name: setup | glimpse | download the tarball
  get_url: url={{ glimpse_download_url }} sha256sum={{ glimpse_csum }}
    dest=~/glimpse.tar.gz force=True
  register: glimpse_downloaded_tarball
  when: lxr_use_search_engine == "glimpse"

- include: inc/build_and_install_tarball.yml
  vars:
    tarball: ~/glimpse.tar.gz
    build_dir: ~/glimpse
    prefix_dir: '{{ glimpse_prefix_dir }}'
    sudo_install: False
  when: lxr_use_search_engine == 'glimpse' and
        ( st.stat.exists == False or st.stat.size == 0 or
          glimpse_downloaded_tarball | changed )
