--- # file: roles/lxr/tasks/150-install_lxr.yml

# Install Lxr

# Assumed remote_user: {{ lxr_user }}

- name: setup | lxr | notice about the tarball
  debug: msg="If the remote tarball is changed,
              sha256sum(csum) must be updated by hand."

- name: setup | lxr | download the tarball
  get_url: url={{ lxr_download_url }} sha256sum={{ lxr_csum }}
    dest=~/lxr.tar.gz force=True
  register: lxr_downloaded_tarball

- name: setup | lxr | cleanup the lxr_dir directory
  file: path={{ lxr_dir }} state=absent
  when: lxr_downloaded_tarball | changed

- name: setup | lxr | prepare the lxr_dir directory
  file: path={{ lxr_dir }} state=directory

- name: setup | lxr | untar the tarball
  command: tar -xzf ~/lxr.tar.gz -C {{ lxr_dir }} --strip-components=1
  when: lxr_downloaded_tarball | changed

- name: setup | lxr | check the environment
  command: chdir={{ lxr_dir }} ./genxref --checkonly
  register: lxr_envchk_result
  changed_when: False

- debug: var=lxr_envchk_result.stdout_lines

