--- # file: roles/lxr/tasks/160-config_lxr.yml

# Configure Lxr

# Assumed remote_user: {{ lxr_user }}

- name: setup | lxr_config | generate the pexpect script
  template: src=gen-configure-lxr.j2 dest=~/gen-configure-lxr.py mode=0755
  register: genscript

- name: setup | lxr_config | check if lxr.conf exists in lxr_custom_dir
  stat: path={{ lxr_custom_dir ~ "/lxr.conf" }}
  register: st

- name: setup | lxr_config | determine if lxr_config need to update
  set_fact:
    update_lxr_config: "{{ st.stat.exists == False or st.stat.size == 0 or
                           genscript | changed }}"

- name: setup | lxr_config | dump lxr.conf and initdb.sh
  command: chdir={{ lxr_user_home }} ~/gen-configure-lxr.py
  when: update_lxr_config

- name: setup | lxr_config | patch the dumped lxr.conf to ignore .git
  lineinfile:
    dest={{ lxr_custom_dir ~ "/lxr.conf" }}
    regexp="^\t, 'ignoredirs'"
    line="{{'\t'}}, 'ignoredirs' => {{ lxr_ignore_dirs }}"
    insertafter="^#\t, 'ignoredirs'"
    state=present
  register: ignoredirs_result

- name: setup | lxr_config | copy the config file to the right place
  command: cp {{ lxr_custom_dir ~ "/lxr.conf" }} {{ lxr_config }}
  when: update_lxr_config or ignoredirs_result | changed

- name: setup | lxr_config | initialize Lxr DB
  shell: creates={{ lxr_db_name }} chdir={{ lxr_custom_dir }} ./initdb.sh

- name: setup | lxr_config | transfer the customized page header
  template: src=html-head-btn.html.j2
    dest={{ lxr_dir ~ "/templates/html/html-head-btn.html" }}
    backup=yes

- name: setup | lxr_config | tranfer the default logo icon for github
  copy: src=GitHub-Mark-64px.png
    dest={{ lxr_dir ~ "/LXRimages/GitHub-Mark-64px.png" }}
