--- # file: roles/lxr/tasks/170-setup_httpd_RedHat.yml

# Setup httpd for Lxr

# Assumed remote_user: root

- name: setup | httpd | patch the config file for httpd_port(1/2)
  lineinfile:
    dest={{ lxr_custom_dir ~ "/apache-lxrserver.conf" }}
    regexp="^NameVirtualHost "
    line="NameVirtualHost *:{{ httpd_port }}"
    state=present
  register: rc1

- name: setup | httpd | patch the config file for httpd_port(2/2)
  lineinfile:
    dest={{ lxr_custom_dir ~ "/apache-lxrserver.conf" }}
    regexp="^<VirtualHost "
    line="<VirtualHost *:{{ httpd_port }}>"
    state=present
  register: rc2

- name: setup | httpd | clean the outdated config file
  file: path={{ httpd_lxr_conf }} state=absent
  when: rc1 | changed or rc2 | changed

- name: setup | httpd | copy the config file to the right place
  command: creates={{ httpd_lxr_conf }}
    cp {{ lxr_custom_dir ~ "/apache-lxrserver.conf" }} {{ httpd_lxr_conf }}
  notify: reload httpd

- name: setup | httpd | set ServerName
  lineinfile:
    dest={{ httpd_main_conf }}
    regexp="^ServerName"
    line="ServerName {{ httpd_server_name ~":"~ httpd_port }}"
    insertafter="^#ServerName "
    state=present
  notify: reload httpd

- name: setup | httpd | set Listen port
  lineinfile:
    dest={{ httpd_main_conf }}
    regexp="^Listen"
    line="Listen {{ httpd_port }}"
    insertafter="^#Listen "
    state=present
  notify: reload httpd

- name: setup | httpd | change the home dir to be world searchable
  file: path=~{{ lxr_user }} state=directory mode=0711

- name: setup | httpd | change glimpse DB dir to be world searchable
  file: path={{ lxr_glimpse_db_dir }} state=directory mode=0755
  when: lxr_use_search_engine == "glimpse"

- name: setup | httpd | change Lxr DB file to be world writable
  file: path={{ lxr_db_name }} state=file mode=0666

