--- # file: roles/lxr/tasks/310-indexing_source_tree.yml

# Index the source code

# Assumed remote_user: {{ lxr_user }}

- include: inc/repo_git_autotag.yml
  when: lxr_tag_name is not defined and source_tree_url | search("git")

- name: indexing | lxr_tag_name to be used
  debug: var=lxr_tag_name

- name: indexing | *** ATTENTION *** 
  debug: msg='Indexing is starting...  
              Indexing can take very long time. Login the target machine
              via {{ lxr_user }} user and run tail -f  
              {{ indexing_progress_file }} to see the progress.'

- name: indexing | index the source directory
  shell: chdir={{ lxr_dir }}
    ./genxref --url={{ httpd_server_url ~ "/lxr/" ~ lxr_tree_name }}
    --version={{ lxr_tag_name }} {{ lxr_genref_opts|default("") }}
    1> {{ indexing_result_file }}
    2> {{ indexing_progress_file }}

- name: indexing | check the file permissions 
  command: find '{{ lxr_glimpse_db_dir }}' -type f '!' -perm '-o+r'
  register: find_result
  changed_when: False

- name: indexing | change the glimpse DB files to be o+r
  file: path={{ item }} state=file mode=0644
  with_items: find_result.stdout_lines
  when: lxr_use_search_engine == "glimpse" and find_result.stdout != ""
