--- # file: roles/lxr/tasks/310-indexing_source_tree.yml

# Index the source code

# Assumed remote_user: {{ lxr_user }}

- include: inc/repo_git_autotag.yml
  when: lxr_tag_name is not defined and source_tree_url | search("git")

- name: lxr_tag_name to be used
  debug: msg={{ lxr_tag_name }}

- name: "attention: indexing is starting"
  debug: msg="Indexing can take very long time. Login to {{ lxr_user }} and
              tail -f {{ indexing_progress_file }} to see the current status."

- name: index the source directory
  shell: chdir={{ lxr_dir }}
    ./genxref --url={{ httpd_server_url ~ "/lxr/" ~ lxr_tree_name }}
    --version={{ lxr_tag_name }} {{ lxr_genref_opts|default("") }}
    1> {{ indexing_result_file }}
    2> {{ indexing_progress_file }}
