--- # file: roles/lxr/tasks/main.yml

# Lxr role's top level main.yml: include and tag the three phases.

# Assumed remote_user: root

- name: determine the appropriate OS file(1/2)
  set_fact:
    osfile: "{{ ansible_os_family ~ ansible_distribution_major_version }}"
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"
  tags: [ setup, tree_retrieval, indexing ]

- name: determine the appropriate OS file(2/2)
  set_fact:
    osfile: "{{ ansible_os_family ~ '6' }}"
  when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
  tags: [ setup, tree_retrieval, indexing ]

- name: include OS dependent variables
  include_vars: "{{ osfile }}.yml"
  tags: [ setup, tree_retrieval, indexing ]

- { include: 100-setup.yml,          tags: setup }
- { include: 200-tree_retrieval.yml, tags: tree_retrieval }
- { include: 300-indexing.yml,       tags: indexing }

- name: url that this role has configured
  debug:
    msg: '{{ httpd_server_url ~ "/lxr/" ~ lxr_tree_name ~ "/source" }}'
  tags: indexing
