--- # file: roles/lxr/tasks/inc/repo_git.yml

# Clone the remote repo to the local and checkout by the specified tag

# Assumed remote_user: {{ lxr_user }}

#---------------------------------------------------------------------------
# Required vars:
#   source_tree_url:     the url of the remote repository to checkout
#   lxr_source_repo_dir: the directory to store the "bare" copy at local
#   lxr_tree_name:       the directory name to store the final source tree
#
# remote: http://github/sample/proj.git
#                                | clone
#                                v
# local: /path/to/source_repo/proj_name.git (bare)
#                                        | checkout
#                                        v
# local: /path/to/source_repo/proj_name/v1.0.1/ (a specific version)
#---------------------------------------------------------------------------


# Minimize the remote data transfer by having the local bare repo.

- name: repo_git | determine the bare repo path
  set_fact:
    bare_repo: '{{ lxr_source_repo_dir ~"/"~ lxr_tree_name ~".git" }}'

- name: repo_git | update the local repository by clone
  git: repo={{ source_tree_url }} remote={{ source_tree_url }}
       dest={{ bare_repo }} bare=yes
  register: clone_result
  until: clone_result | success
  retries: 2        # git sporadically fails, so retry is provided here.
  delay: 3



# Fine out lxr_tag_name from the bare repo if it is undefined.

- include: repo_git_autotag.yml
  when: lxr_tag_name is not defined or lxr_tag_name == ''



# Checkout the target version to the target directory.

- name: repo_git | lxr_tag_name to be used
  debug: var=lxr_tag_name

- name: repo_git | determine the destination repo path
  set_fact:
    dest_repo: '{{ lxr_source_repo_dir ~"/"~ lxr_tree_name ~"/"~ lxr_tag_name }}'

- name: repo_git | checkout by lxr_tag_vcs to dest_repo
  git: repo={{ bare_repo }} version={{ lxr_tag_vcs }}
       dest={{ dest_repo }} depth=1
  register: rc
  ignore_errors: True

- name: repo_git | clean the source tree that seems broken
  file: path={{ dest_repo }} state=absent
  when: rc | failed

- name: repo_git | retry
  git: repo={{ bare_repo }} version={{ lxr_tag_vcs }}
       dest={{ dest_repo }} depth=1
  when: rc | failed
