--- # file: roles/lxr/vars/RedHat6.yml

httpd_version:    '2.2'
httpd_main_conf:  '/etc/httpd/conf/httpd.conf'
httpd_lxr_conf:   '/etc/httpd/conf.d/apache-lxrserver.conf'

# EPEL repository package
Fedora_site: 'http://dl.fedoraproject.org/pub'
EPEL_repo_pkg: '/epel/6/x86_64/epel-release-6-8.noarch.rpm'
EPEL_repo_url: '{{ Fedora_site ~ EPEL_repo_pkg }}'
